baseurl = "https://gourabdg47.github.io/Blog/"
languageCode = "en-us"
title = "A Strange Blog"
theme = "ghostwriter"
paginate = 5

[Params]
    mainSections = ["post"]
    intro = true
    headline = "A Confused Mind"
    description = "Walk with me through space And time ..."
    github = "https://github.com/gourabdg47"
    twitter = "https://twitter.com/Gourabparadox47"
    email = "gourabdasgupta26994@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
